title: 16th Annual International Biocuration Conference
email: biocuration2023@gmail.com

theme: minima
github_username: biocuration2023
twitter_username: biocuration2023

plugins:
  - jekyll-feed
  - jekyll-sitemap
